### ISSUE TITLE
Find a new maintainer and transfer the repo?

### ISSUE THREAD

**Issue by andybak** [awesome-NeRF/awesome-NeRF#108]
There's some good PRs but no updates in several months.

I volunteer to be a temporary custodian if it moves things forward but I'm sure there are better qualified people who would be happy to take over.

**Comment by yenchenlin** [comment]
That sounds good! What's the best way to forge ahead? Should I create a new shared account *awesome-nerf* and forward this project there?

**Comment by andybak** [comment]
That would work. Create a new Github org and use "Transfer Repo" under
Settings.

(Strictly speaking there's no need to transfer it - if you don't mind
staying in the loop enough to make a call on who gets commit rights as the
baton is passed around?)

**Comment by yenchenlin** [comment]
Hello @andybak , I have transferred the repo to an organization to show that this is a collective effort moving forward. I've invited you to become a collaborator.
