### ISSUE TITLE
CVPR 2023 highlight

### ISSUE THREAD

**Issue by zhangmozhe** [awesome-NeRF/awesome-NeRF#121]
Thanks for this awesome project. Could you please add our CVPR 2023 highlight paper: Rodin: A Generative Model for Sculpting 3D Digital Avatars Using Diffusion? The paper is about generating nerf using diffusion model.

Arxiv: https://arxiv.org/abs/2212.06135
Project page: https://3d-avatar-diffusion.microsoft.com/

**Comment by andybak** [comment]
Hi there, Happy to add you but can you do it via a pull request?

See https://github.com/awesome-NeRF/awesome-NeRF/blob/main/how-to-PR.md

**Comment by tares003** [comment]
@zhangmozhe code is not public dahhh

**Comment by zhangmozhe** [comment]
The pull request has been merged. Thanks!
