### ISSUE TITLE
Inclusion Request for Customizable SLAM Robustness Benchmark (NeRF vs Gaussian Splatting representation for instant 3D reconstruction and localization)

### ISSUE THREAD

**Issue by Xiaohao-Xu** [awesome-NeRF/awesome-NeRF#149]
Hey guys,

We sincerely appreciate the value of your repository! We would like to kindly request the inclusion of our **customizable SLAM robustness benchmark**, which incorporates a noisy data simulation pipeline for a comprehensive evaluation of SLAM performance. Our benchmark mainly focuses on **evaluating the robustness of the latest monocular/multi-modal Neural-based SLAM models**, including **NeRF-based and Gaussian-Splatting-based** SLAM, which reveals **some intriguing properties of NeRF and GS representation** for instant 3D reconstruction and localization. Additionally, it offers a preliminary assessment of multi-view and multi-agent/collaborative SLAM robustness.

We are confident that the addition of our benchmark will contribute to making SLAM more deployable and robust. We greatly appreciate your consideration. Thanks!

* **Customizable-SLAM**: Customizable Perturbation Synthesis for Robust SLAM Benchmarking, ArXiV, 2024. [[Paper](https://arxiv.org/abs/2402.08125)] [[Code](https://github.com/Xiaohao-Xu/SLAM-under-Perturbation)] [[Video](https://www.youtube.com/watch?v=jNM94naSPXA)]

**Comment by andybak** [comment]
Instructions for submitting pull requests are in the readme.

**Comment by Xiaohao-Xu** [comment]
Got that. Thanks!
