### ISSUE TITLE
NeRF Pose Estimation

### ISSUE THREAD

**Issue by chenusc11** [awesome-NeRF/awesome-NeRF#151]
Hi, Lin. Thanks for the great work! Really appreciate for this awesome repo

Could you please kindly add some more nerfs to pose estimation? Many thanks!

**Neural Refinement for Absolute Pose Regression with Feature Synthesis (CVPR 2024)**
Project web: https://nefes.active.vision/
Github: https://github.com/ActiveVisionLab/NeFeS

**PoRF: Pose Residual Field for Accurate Neural Surface Reconstruction (ICLR 2024)**
Project web: https://porf.active.vision/
Github: https://github.com/ActiveVisionLab/porf/

**CROSSFIRE: Camera Relocalization On Self-Supervised Features from an Implicit Representation (ICCV 2023)**
https://arxiv.org/abs/2303.04869

**NoPe-NeRF: Optimising Neural Radiance Field with No Pose Prior (CVPR 2023 Highlight)**
Project web:  https://nope-nerf.active.vision/
Github: https://github.com/ActiveVisionLab/nope-nerf/

**GARF: Gaussian Activated Radiance Fields for High Fidelity Reconstruction and Pose Estimation (ECCV 2022)**
https://arxiv.org/abs/2204.05735

**DFNet: Enhance Absolute Pose Regression with Direct Feature Matching (ECCV 2022)**
Project web: https://dfnet.active.vision/
Github: https://github.com/ActiveVisionLab/DFNet

**Comment by andybak** [comment]
Hi. Could you make this into a pull request? 

See https://github.com/awesome-NeRF/awesome-NeRF/blob/main/how-to-PR.md

**Comment by chenusc11** [comment]
@andybak Awesome!
I have created a pull request.
https://github.com/awesome-NeRF/awesome-NeRF/pull/152

Thanks for the effort!
