### ISSUE TITLE
Wrong author info

### ISSUE THREAD

**Issue by jeongyw12382** [awesome-NeRF/awesome-NeRF#92]
Hi. Thanks for the great repository. 
Indeed, I found an error on author information of my publication. 
Could you change the main author of Self-calibrating Neural Radiance Fields from Jaesik to Yoonwoo? 
In detail, 
> [Self-Calibrating Neural Radiance Fields](https://postech-cvlab.github.io/SCNeRF/), Park et al., ICCV 2021 | [github](https://github.com/POSTECH-CVLab/SCNeRF) | [bibtex](https://github.com/yenchenlin/awesome-NeRF/blob/main/citations/SCNeRF.txt) ->  [Self-Calibrating Neural Radiance Fields](https://postech-cvlab.github.io/SCNeRF/), Jeong et al., ICCV 2021 | [github](https://github.com/POSTECH-CVLab/SCNeRF) | [bibtex](https://github.com/yenchenlin/awesome-NeRF/blob/main/citations/SCNeRF.txt)

Thanks.

**Comment by yenchenlin** [comment]
Hello @jeongyw12382 , sincerely sorry about that.

**Comment by yenchenlin** [comment]
Does it look right now? Again, my bad.

**Comment by andybak** [comment]
Closing. Going to assume this is correct now.
