### ISSUE TITLE
Looking forward to updating

### ISSUE THREAD

**Issue by SimonCK666** [awesome-NeRF/awesome-NeRF#98]
Very Looking forward to seeing updateing the NeRF recently papers

Best!

**Comment by salykovaa** [comment]
Hi @SimonCK666

I have created today a [repository](https://github.com/salykovaa/awesome-nerf), containing latest NeRF-related works, tutorials, lectures, codebases etc (most of them from 2022 and 2021). The repo will be frequently updated and maintained by me. There is already good portion of NeRF works, but I will add more in next couple of days. Please take a look, maybe you will find it interestring!

It seems, that after such a long break, this repo will not be maintained/updated by @yenchenlin
